package no.norrs.nortools.web

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class NetworkInterfacesLinuxParsingTest {

    @Test
    fun `parses linux ip route rows including default route`() {
        val raw = """
            default via 192.168.1.1 dev wlp2s0 proto dhcp metric 600
            192.168.1.0/24 dev wlp2s0 proto kernel scope link src 192.168.1.111 metric 600
            10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.2
        """.trimIndent()

        val routes = parseRoutes(raw)
        assertEquals(3, routes.size)
        assertEquals("default", routes[0].destination)
        assertEquals("192.168.1.1", routes[0].gateway)
        assertEquals("wlp2s0", routes[0].interfaceName)
    }

    @Test
    fun `parses linux resolvectl interface dns and default dns`() {
        val raw = """
            Global
                     Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

            Link 2 (wlp2s0)
                Current Scopes: DNS
                     Protocols: +DefaultRoute
           Current DNS Server: 192.168.1.1
                  DNS Servers: 192.168.1.1 1.1.1.1

            Link 6 (tun0)
                Current Scopes: DNS
                     Protocols: +DefaultRoute
                  DNS Servers: 10.8.0.1
        """.trimIndent()

        val (interfaceDns, defaultDns) = parseLinuxResolvectlDns(raw)
        assertEquals(listOf("192.168.1.1", "1.1.1.1"), interfaceDns["wlp2s0"])
        assertEquals(listOf("10.8.0.1"), interfaceDns["tun0"])
        assertTrue(defaultDns.contains("192.168.1.1"))
        assertTrue(defaultDns.contains("1.1.1.1"))
        assertTrue(defaultDns.contains("10.8.0.1"))
    }

    @Test
    fun `parses resolv conf nameservers`() {
        val text = """
            # generated by NetworkManager
            nameserver 192.168.1.1
            nameserver 1.1.1.1
            search example.local
        """.trimIndent()

        val dns = parseResolvConfNameserversText(text)
        assertEquals(listOf("192.168.1.1", "1.1.1.1"), dns)
    }
}
